name: Linux Debug Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  linux-debug:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake clang ninja-build libc++-dev libc++abi-dev xorg-dev libglu1-mesa-dev

      - name: Configure
        run: cmake --preset clang-libcxx-ninja-debug

      - name: Build
        run: cmake --build --preset clang-libcxx-ninja-debug --parallel 4

      - name: Run tests
        run: ctest --preset clang-libcxx-ninja-debug
