# Simple workflow for deploying static content to GitHub Pages
name: Deploy test coverage report to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake clang llvm ninja-build xorg-dev libglu1-mesa-dev lcov

      - name: Configure
        run: cmake --preset clang-ninja-debug

      - name: Build
        run: cmake --build --preset clang-ninja-debug --parallel 4

      - name: Run tests and generate coverage
        run: |
          cat > /tmp/llvm-gcov.sh <<'EOF'
          #!/usr/bin/env bash
          exec llvm-cov gcov "$@"
          EOF
          chmod +x /tmp/llvm-gcov.sh
          ctest --preset clang-ninja-debug
          lcov --gcov-tool /tmp/llvm-gcov.sh --directory build/clang-ninja-debug --capture --output-file build/clang-ninja-debug/coverage.info --keep-going --ignore-errors gcov,inconsistent
          lcov --extract build/clang-ninja-debug/coverage.info '*/source/*' --output-file build/clang-ninja-debug/coverage-src.info --ignore-errors gcov,inconsistent
          genhtml -o build/clang-ninja-debug/coverage build/clang-ninja-debug/coverage-src.info --ignore-errors inconsistent,unsupported,category

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './build/clang-ninja-debug/coverage'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
