name: Windows Debug Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  windows-debug:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Configure
        run: cmake --preset clang-cl-vs-debug

      - name: Build
        run: cmake --build --preset clang-cl-vs-debug --parallel 4

      - name: Run tests
        run: ctest --preset clang-cl-vs-debug
